# Generated by Django 4.1.3 on 2022-12-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='pay',
            field=models.TextField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
