# Generated by Django 4.1.3 on 2022-11-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_image", models.ImageField(upload_to="")),
                ("product_name", models.CharField(max_length=120)),
                ("product_price", models.IntegerField(default=100)),
                ("deliveryDay", models.CharField(max_length=120)),
                ("delTimeFrom", models.DateTimeField()),
                ("delTimeTo", models.DateTimeField()),
            ],
        ),
    ]
