# Generated by Django 4.1.3 on 2022-12-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HaideriGreens", "0002_product_fruit_product_veggie_user_delete_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisteredUser",
            fields=[
                ("User_id", models.AutoField(primary_key=True, serialize=False)),
                ("Username", models.CharField(max_length=30)),
                ("Email", models.EmailField(max_length=120)),
                ("Password", models.CharField(max_length=10)),
                ("DOB", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
