# Generated by Django 4.1.3 on 2022-11-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0002_alter_product_mfc_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_price",
            field=models.IntegerField(default=100),
        ),
    ]
