# Generated by Django 4.1.3 on 2022-11-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_product_date_product_description_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='email',
        ),
    ]
