# Generated by Django 4.1.3 on 2022-11-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_type_product_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='email',
            new_name='type',
        ),
    ]
